homeassistant:

  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret duckdnsapi_password

  # Name of the location where Home Assistant is running
  name: Casa Inteligente
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_casa
  longitude: !secret longitude_casa
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 93
  # metric for Metric, imperial for Imperial
  unit_system: metric
  ## C FOR CELCIUS, F FOR FAHRENHEIT
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Packages
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

webhook:
 
zigbee2mqtt_networkmap:
#topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret url_tasmoadmin

  mdiindex:
    title: MDI icons
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

# Enables configuration UI
config:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key
      host: !secret xiaomi_host

mqtt:
  broker: !secret mqtt_broker_ip
  port: 1883
  client_id: armhassio
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1.1
  discovery: true


notify:
  - name: telegram
    platform: telegram
    chat_id: !secret chat_ids_bruno

  - platform: nfandroidtv
    name: TV Sala
    host: !secret ip_formuler_android_tv
    duration: 10
    fontsize: large
    position: top-right

  - platform: nfandroidtv
    name: Mi box s
    host: !secret ip_mibox_android_tv
    duration: 10
    fontsize: large
    position: top-right
    
telegram_bot:
  - platform: polling
    api_key: !secret api_key_bruno
    allowed_chat_ids:
      - !secret chat_ids_bruno

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1-254
    home_interval: 6

  - platform: ping
    hosts:
      bruno_melo: !secret bruno_melo_ip
      armanda_rodrigues: !secret armanda_rodrigues_ip
      armando_melo: !secret armando_melo_ip
      samsung_smart_tv: ! secret ip_samsung_tv
      xiaomi_mi_box_s_2: !secret ip_mibox_android_tv
      count: 2

http:
#  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3


samsungtv:
  - host: !secret ip_samsung_tv

media_player:

  - platform: androidtv
    name: Mi Box S
    host: !secret ip_mibox_android_tv
    device_class: androidtv
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

#  - platform: androidtv
#    name: Formuler z7plus
#    host: !secret ip_formuler_android_tv
#    device_class: androidtv
#    adb_server_ip: 127.0.0.1
#    adb_server_port: 5037

  - platform: mediaroom
    host: !secret ip_box_cozinha
    name: "vodafone Cozinha"

  - platform: mediaroom
    host: !secret ip_box_bruno
    name: "vodafone Bruno"

  - platform: mediaroom
    host: !secret ip_box_sala_pai
    name: "vodafone Quarto"

google_assistant:
  project_id: imperial-rarity-260700
  service_account:
    private_key: nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChl8QVCG7PNdQY\neKMoEowHx3RPyksuVu5kHNInBubiV9TciVH1/D4vth3U4DMpROUbEGCJCwXS2m0B\n+sK4EMKYr6Cck98kYWFWQHun44hDenS7li3egomQVkRywH20i87b1BRqeX1Cv867\nV3QiTeSKBIKNCia+2ER1wXvmaz/DnapuhNVq4srSrYkh2DHuTb+VXtqySomw0+Rw\n+gqKYmrZ/6fhqyfExXOi9/0K9DfUdqeYtxVVdHuJFm7n0wiT3dNmsTDhFE+KhDF+\nAK0vEOi+992dCYXoyXIA4GlnIfaYsFdzxy9VL9c4G4hsNNXfszw5a4ehiuI9pbZl\nJ8FPI4ntAgMBAAECggEAG35Va9iz9chsTj+UTvic36P1a6/5C6jZxanLrb00YlVc\nT6uDiO1CbV64g6QjwEVLD8hBDIAWHRJx0pDmOWgMm+rh0lIseKWi6IhvIZkKcaSv\noM0D/+RI4Ih0++s5WBMjfm5+jMEf6U/2LhTKmx2SoVL0HWgZQIZOW5SwbntX7YGr\n+MvwsrA8XXQoe5rbLqew9onIdenOxdpWKkzetPYZloPJyOUun7tRsHmGILrtErQv\niGZYAkC2vejvOm6SKHQ1ZoZd1pwsrgwLZwRZJyBg62zPlY4/ek5qRijl4BZKL8e6\nd51gS91XLlVqwERnhMjLgY7PyOMdwgeptvb1LFOjpwKBgQDbfXvC1bHemS8MZwDZ\nQK1T9U4hoWVo130ITWvnV/7rh9nA0fw8ltRuoBkexiniWKnpJVEB9BVyl4x5EsjR\n1H+U4l3phtGVsExf2LeyKtwsobtfpP115K45LrWHcywfyvsZV0J8K08UektbVvWV\nQRpKN/qNOK1buF9npY5lWxvJewKBgQC8eNlgTmNlYmICLqXr4IpO/ZfSqQwM5O5O\nVPYa+0T79ec3/HTJemr9L+M0ftQYiXc3uklJpvz0s+EnZyRCImomzohraNyuBg1n\ncAy+pbgXaePKj9pyv5DcK3YJbj7dOAgAs2ILvm2z3DspSmSH2CLRDUrKRbfNF46n\n84EoW9SZtwKBgB19JXSOy1/xyr1q1VVa+C6QhZfFHF/Sm8zSwg2J6Ajy7pGWZMIr\nLY1TWyykSRpM+T8GsXSGu57yt3/Iw0xVtXJmW2G1qFDpJ8m0zzFTytMAQ7Fc9GSz\nfajXGrKBCcuXtNa5v4f5NZ21tIwoCcSsw4B3NuVkWP46ri65soDxlbEjAoGBAIGH\niNXwac125SbcynmnE0cgcGR+e+Ksv78kExQOFqYXpXZL0jPaJ4ekjsE4XSoT59Rr\n+gxdcMH4kkhTUY8GOfA7x3QSWIBddn7delTYbgHha4V+gkKUt8kpMXFfzGKbLJzW\nrA6oLJsNQ7eoAhl+iMcmHH2RlrWkeA2jg+Op4R5XAoGABBL0ZrXhbmI57jUsENvB\nP7rEQqNMaSWdnOKU8yjDVNEv6Ifi4x7xDjRBJJUWyig7g12LnChntIWjvlpE37tK\nz4l2KDQT74OpsdaGVoVI10oHqdsZ69IUud+ETAPOID9/FBBbSEuuSH2frsdm1te4\nFeywkrG3GwYkpy9fmcPgePU=
    client_email: hassiogam@imperial-rarity-260700.iam.gserviceaccount.com
  report_state: true
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - group
    - cover
    - vacuum
    - script

#### GOOGLE CAST
cast:
  media_player:
    - host: !secret ip_google_home_mini
    - host: !secret ip_mibox_android_tv

# hacs #
hacs:
  token: !secret hacs_token

#breaking changes HA
breaking_changes:
  name: Potenciais alterações
  scan_interval: 60

#octoprint
octoprint:
  host: 192.168.1.82 # use IP address of your OctoPi
  api_key: !secret octo_api
  name: Geeetech A10 # this is not mandatory
  bed: true # set tu true if your printer has heated bed
  number_of_tools: 1 # if you have only one hot-end

camera:
  - platform: mjpeg
    name: OctoCamera
    still_image_url: http://192.168.1.82/webcam/?action=snapshot
    mjpeg_url: http://192.168.1.82/webcam/?action=stream

mobile_app:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free

# Cloud
cloud:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'pt'
    cache: true
    base_url: !secret duckdnsbase_url

group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml


#https://forum.homeassistantbrasil.com.br/t/configurar-o-google-assistant-para-home-assistant/132