homeassistant:

#Authentication
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        #- 127.0.0.1
        - 192.168.1.0/24

  # Name of the location where Home Assistant is running
  name: Casa Inteligente
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_casa
  longitude: !secret longitude_casa
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 10
  # metric for Metric, imperial for Imperial
  unit_system: metric
  ## C FOR CELCIUS, F FOR FAHRENHEIT
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Packages
  packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

webhook:
 
zigbee2mqtt_networkmap:
#topic: your topic (optional, default zigbee2mqtt)
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret url_tasmoadmin

  mdiindex:
    title: MDI icons
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

# Enables configuration UI
config:

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_mac
      key: !secret xiaomi_key
      host: !secret xiaomi_host

mqtt:
  broker: !secret mqtt_broker_ip
  port: 1883
  client_id: armhassio
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1.1
  discovery: true


notify:
  - name: telegram
    platform: telegram
    chat_id: !secret chat_ids_bruno

  - platform: nfandroidtv
    name: TV Sala
    host: !secret ip_formuler_android_tv
    duration: 10
    fontsize: large
    position: top-right

  - platform: nfandroidtv
    name: Mi box s
    host: !secret ip_mibox_android_tv
    duration: 10
    fontsize: large
    position: top-right
    
telegram_bot:
  - platform: polling
    api_key: !secret api_key_bruno
    allowed_chat_ids:
      - !secret chat_ids_bruno

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1-254
    home_interval: 6

  - platform: ping
    hosts:
      bruno_melo: !secret bruno_melo_ip
      armanda_rodrigues: !secret armanda_rodrigues_ip
      armando_melo: !secret armando_melo_ip
      samsung_smart_tv: ! secret ip_samsung_tv
      xiaomi_mi_box_s_2: !secret ip_mibox_android_tv
      count: 2

http:
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

media_player:

  - platform: samsungtv
    name: Samsung Smart TV
    host: !secret ip_samsung_tv

  - platform: androidtv
    name: Mi Box S
    host: !secret ip_mibox_android_tv
    device_class: androidtv
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

  - platform: androidtv
    name: Formuler z7plus
    host: !secret ip_formuler_android_tv
    device_class: androidtv
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

  - platform: mediaroom
    host: !secret ip_box_cozinha
    name: "vodafone Cozinha"

  - platform: mediaroom
    host: !secret ip_box_bruno
    name: "vodafone Bruno"

  - platform: mediaroom
    host: !secret ip_box_sala_pai
    name: "vodafone Quarto"

#Google Home Mini Integration
google_assistant:
  project_id: !secret project_id
  api_key: !secret ghm_api_key
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - group
    - cover
    - vacuum
    - script

#### GOOGLE CAST
cast:
  media_player:
    - host: !secret ip_google_home_mini
    - host: !secret ip_mibox_android_tv

# hacs #
hacs:
  token: !secret hacs_token

#breaking changes HA
breaking_changes:
  name: Potenciais alterações
  scan_interval: 60


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'

# Cloud
cloud:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'pt'
    cache: true
    base_url: !secret duckdnsbase_url

group: !include groups.yaml
#automation: !include automations.yaml
script: !include scripts.yaml
