homeassistant:

###############################################################################

#                                                                             #

#                           C U S T O M I Z E                                 #

#                                                                             #

###############################################################################   

        

#  customize:




###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  

#lights:



###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             
###############################################################################      

group:

  Ligar Automações:
    control: hidden
    entities:
      - automation.iluminacao_sala_17h0019h30
      - automation.iluminacao_sala_19h3020h30
      - automation.iluminacao_sala_20h3021h30
      - automation.iluminacao_sala_21h3022h30
      - automation.mudar_fraldas_sala_on
      - automation.mudar_fraldas_quarto_on
      - automation.liga_luz_do_exterior
      - automation.liga_luz_do_gateway
      

  Desligar Automações:
    control: hidden
    entities:
      - automation.sala_off_17h19h30
      - automation.sala_off_19h3020h30
      - automation.sala_off_20h3021h30
      - automation.sala_off_21h3022h30
      - automation.mudar_fraldas_sala_off
      - automation.mudar_fraldas_quarto_off
      - automation.desliga_luz_do_gateway
      - automation.desliga_luz_do_exterior
      - automation.desligar_candeeiros_a_cima_dos_20_lx
      
  automacoes:
    view: yes
    name: Automações
    entities:
      - group.ligar_automacoes
      - group.desligar_automacoes