homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      
input_boolean:

  battery_notifications:
    name: Notificações da bateria
    initial: 'on'
    icon: 'mdi:battery-charging-wireless'

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

  - alias: Substituir a Bateria dos Sensores
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id:
        - sensor.sensor_porta_entrada_battery_level
        - sensor.sensor_portao_entrada_battery_level
        - sensor.sensor_portao_jardim_battery_level
        - sensor.sensor_movimento_sala_battery_level
        - sensor.sensor_movimento_quarto_battery_level
        - sensor.sensor_movimento_cozinha_battery_level
        - sensor.sensor_temperatura_sala_battery_level
        - sensor.cubo_magico_battery_level
        - sensor.interruptor_battery_level
      below: 10
    action:
      - service: notify.telegram
        data_template:
          title: "Sensores a ficar sem bateria"
          message: "{{ trigger.to_state.attributes.friendly_name }} está a {{ trigger.to_state.attributes.battery_level | default(0) }}%"

###############################################################################
#                                                                             #
#                           S E N S O R E S                                   #
#                                                                             #
###############################################################################

sensor:

  - platform: template
    sensors:
      sensor_porta_entrada_battery_level:
        friendly_name: Porta entrada
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d00022b3ad2.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d00022b3ad2.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}



      sensor_porta_escritorio_battery_level:
        friendly_name: Sensor porta do Escritório
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d00024e0c7b.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d00024e0c7b.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      sensor_portao_entrada_battery_level:
        friendly_name: Sensor portão entrada
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d0002729eba.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0002729eba.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      sensor_portao_jardim_battery_level:
        friendly_name: Sensor portão jardim
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.door_window_sensor_158d0002bf9d6d.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0002bf9d6d.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      sensor_movimento_sala_battery_level:
        friendly_name: Sensor de movimento Sala
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d0001f9d417.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d0001f9d417.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      sensor_movimento_quarto_battery_level:
        friendly_name: Sensor de movimento quarto
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d000272b7c0.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d000272b7c0.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      sensor_movimento_cozinha_battery_level:
        friendly_name: Sensor de movimento cozinha
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d00029be9c3.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d00029be9c3.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      sensor_movimento_despensa_battery_level:
        friendly_name: Sensor de movimento despensa
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.motion_sensor_158d0002f8d190.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d0002f8d190.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      sensor_temperatura_sala_battery_level:
        friendly_name: Sensor de temperatura sala
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.sensor.temperature_158d00023203e4.attributes.battery_level %}
            {{ states.sensor.temperature_158d00023203e4.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      cubo_magico_battery_level:
        friendly_name: Cubo mágico
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.cube_158d00027984b3.attributes.battery_level %}
            {{ states.binary_sensor.cube_158d00027984b3.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
      interruptor_battery_level:
        friendly_name: Interruptor
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.switch_158d00015aa37d.attributes.battery_level %}
            {{ states.binary_sensor.switch_158d00015aa37d.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

      sensor_chuva_battery_level:
        friendly_name: Sensor de Chuva
        unit_of_measurement: '%'
        value_template: >-
          {%- if states.binary_sensor.water_leak_sensor_158d00024bc707.attributes.battery_level %}
            {{ states.binary_sensor.water_leak_sensor_158d00024bc707.attributes.battery_level|round }}
          {% else %}
            {{ states.sensor.door_sensor.state }}
          {%- endif %}
        icon_template: >
          {% set battery_level = states.sensor.door_sensor.state|default(0)|int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}