homeassistant:

###############################################################################
#                                                                             #
#                           S W I T C H                                       #
#                                                                             #
###############################################################################
switch:
  - platform: broadlink
    host: !secret ip_broadlink
    mac: '78:0F:77:D9:0C:02'
    type: 'rm_mini'
    friendly_name: 'Broadlink RM 3 Mini'
    switches:
      samsung_tv:
        friendly_name: "Samsung TV"
        command_on: 'JgAcAZWWETkSOBI4EhQRFBAVERQRFBI4ETkSORAVEBURFBITERQRFBE6EBUQFRAVERQRFBEUETkSFBE5EDoRORI4EToQOhEAAh8UAAPek5cRORE6EDoRFBEUERQRFBEUEjkRORE5ERQRFBEUERUQFRAVEDoSExEUERQSExEVEBUQOhEUETkSOBE6ETkRORE5EgAGEJWWETkRORI4ERQSFBAVEBURFBE5EjgROBMUEBURFBEUERQRFBE6ERQQFRAVERQRFBEUETkRFRE5ETkSOBE5EToROREABhGUlhI4EjkRORAVERQRFBEUEhMROhE5ETkSExEUERQRFBEVEBUQOhEUERQRFBEUERQRFRA6EBURORI4EjgROhA6ETkRAA0FAAAAAAAAAAAAAAAA'
        command_off: 'JgAYAZWWEDoRORE5EhMSExEVEBUQFRE5EjgSOBIUEBUQFREUERQRFBE5ERQSExEVEBUQFREUETkSExE5EjkRORE5EjgRORIABhCVlhE5ETkSOBEUERUQFRAVERQRORE5ETkSFBAVEBURFBEUERQRORITERUQFRAVERQRFBE5ERQROhE5ETkSOBE5EToRAAYQlZYRORI4EToQFRAVERQRFBEUETkSORE5ERQRFBITERQRFBEVEDoQFREUEhMRFBEUERQROhAVETkRORE5ETgTORE5EgAGDpeWETkSOBI4EhQQFRAVERQSExE5EjgROhEUERQRFBEUEhMRFBE6EBURFBEUERQRFBEUEToRFBA6ETkRORI5ETkROREADQU='
    
      samsung_tv_hdmi1:
        friendly_name: "Samsung TV HDMI1"
        command_on: 'JgDSAJOVEzYUNxI3EhQSEhITEhQRExI4EjgSOBITEhITExISEhMSOBIUERMSOBITEjgTNxI4EhMRORE5ERQSOBITEhISExIABgOUlBM3EjgSNxMTEhISExITExISOBI4EjgSExITEhMSExETEzcTExISEjgSExI4EjgSOBMSEjgSOBEUEjgSExISEhQSAAYCk5USOBI4EjgSExISEhMSExITEjgSOBI4EhMRFBITEhITExI3ExMSEhI4EhMRORI4EjgSExI4EjgSExI4EhMSEhIUEgANBQAAAAAAAA=='

      samsung_tv_hdmi2:
        friendly_name: "Samsung TV HDMI2"
        command_on: 'JgDSAJOVEjgSOBI3ExMRExMSEhMSExI4EjgTNxITERQSExISExISExI4EjgSOBM4ETkSEhI3EzgSExISEhQSExETEjgSFBEABgOTlRE5EjgSOBMSEhISExITEhMSOBI4EjgSExEUEhMRExIUERMSOBI4EzcSOBI5EhISOBI4ExITERMTEhMRExI4EhQRAAYDk5USOBI4EjgSExETEhQSEhITEjgSOBM3EhMSExMSERMSFBISEjgSOBI4EjgSORETEjgSOBITEhMSExMREhMTNxMTEQANBQAAAAAAAA=='

      samsung_tv_hdmi3:
        friendly_name: "Samsung TV HDMI3"
        command_on: 'JgDSAJOVEzcTNxI4EhMSEhIUEhISExI4EzcSOBITEhMSExITEhMTEhI4ERMSFBISEhMSOBI4EjgTEhI4EjgSOBI4EhMSExIABgKUlBI4EjgSOBMSExETExISEhMTNxI4EjgSFBISEhMSExITEhMRORETExMRExITEjgSOBI1FhISOBI4EjgSOBITEhMSAAYCk5USOBI4EjgSExITEhMSEhITEjgTNxM3ExMSEhITEhMSExISEjkRExIUEhISExI4EjgSOBMSEjgSOBI4EjgTEhITEgANBQAAAAAAAA=='

      samsung_tv_hdmi4:
        friendly_name: "Samsung TV HDMI4"
        command_on: 'JgDSAJKWEjgSOBI4EhMRFBITEhMQFBQ2EjgSOBIUEBQSExITEhMSOBITEDoRExIUERMRORI4EhMSOBITEzcSOBE3ExQSExIABgKTlRI4EjgRORITEhMTEhEUEBQTNxM3EzcSFBETEhMSExITEjgSExE5ERMTExETEjgSNxMTETkSFBA5EjgSOBITEhMRAAYEkpUTNxI4EzcSExITEhMTEhEUETkSNxM3ExMRExITEhMSExI4EhMROREUERQRExE5EjgSExI4EhMSORE5ETgSExITEgANBQAAAAAAAA=='