homeassistant:
###############################################################################
#                                                                             #
#                           switch                                            #
#                                                                             #
###############################################################################
switch:

  - platform: mqtt
    name: "Cameras de Vigilância"
    state_topic: "shellies/shelly1-BA5BB5/relay/0"
    command_topic: "shellies/shelly1-BA5BB5/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: true