homeassistant:

###############################################################################

#                                                                             #

#                           C U S T O M I Z E                                 #

#                                                                             #

###############################################################################   

###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

# automação despensa


###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  



###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################      

group:

  iluminacao despensa:
    control: hidden
    name: Iluminação da Despensa
    entities:
      - light.yeelight_rgb_7811dc6b09nm
      
  automacao:
    control: hidden
    name: Automações da Despensa
    entities:
      - automation.ligar_despensa
      - automation.desligar_despensa

  despensa:
    view: yes
    name: Despensa
    entities:
      - group.iluminacao_despensa
      - group.automacao