homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    light.yeelight_color1_7811dcaa58c8:
      friendly_name: Aplique da Despensa
      icon: mdi:lightbulb-on
    binary_sensor.0x00158d0002f8d190_occupancy:
      friendly_name: Sensor Despensa
      icon: mdi:run
    sensor.0x00158d0002f8d190_illuminance:
      friendly_name: Sensor LX Despensa
      icon: mdi:brightness-4

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  
yeelight:
  devices:
    !secret yeelight_despensa:
      name: yeelight_color1_7811dcaa58c8
      model: color1
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

# automação despensa

  - alias: Ligar aplique despensa 00h 06h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.0x00158d0002f8d190_occupancy
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '00:00:00'
      before: '06:00:00'
    - condition: numeric_state
      entity_id: sensor.0x00158d0002f8d190_illuminance
      below: 60
    action:
      - service: light.turn_on
        entity_id: light.0x680ae2fffec92973_light
        data:
          brightness: 80

  - alias: Ligar aplique despensa 06h 00h
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.0x00158d0002f8d190_occupancy
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '06:00:00'
      before: '00:00:00'
    - condition: numeric_state
      entity_id: sensor.0x00158d0002f8d190_illuminance
      below: 60
    action:
      - service: light.turn_on
        entity_id: light.0x680ae2fffec92973_light
        data:
          brightness: 255

  - alias: Desligar aplique despensa
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.0x00158d0002f8d190_occupancy
      from: 'on'
      to: 'off'
      for:
        minutes: 2
    action:
      - service: light.turn_off
        entity_id: light.0x680ae2fffec92973_light