homeassistant:

###############################################################################

#                                                                             #

#                           C U S T O M I Z E                                 #

#                                                                             #

###############################################################################   

        

#  customize:




###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#automação despensa

  - alias: liga luz despensa
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensorvcv.door_window_sensor_158d00022b3ad2
      to: 'on'
    condition:
      condition: time
      after: '19:00:00'
      before: '07:30:00'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.despensa
          brightness: 100
          color_name: deepskyblue

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  



###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################      

group:

  despensa:
    view: yes
    name: despensa
    entities:
      - group.despensagrupo

      

  despensagrupo:
    control: hidden
    name: Despensa
    entities:
      - light.despensa
