homeassistant:

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#Faz um backup total do hassio às 03:00 am.
  - alias: Backup hassio 03 am
    initial_state: false
    trigger:
      platform: time
      at: '03:00'
    action:
    - service: hassio.snapshot_full
      data_template:
        name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
        
        
# Envia para a minha conta Gdrive o backup do hassio às 04:00 da manhã.
  - alias: Envio Dropbox 04 am
    trigger:
      platform: time
      at: '4:00'
    action:
    - service: rest_command.google_backup
    
rest_command:
  google_backup:
    url: 'http://192.168.1.250:8055/gb/doBackup'
    timeout: '300'