homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#automaçóes gatewayy

  - alias: Liga Luz do Gateway
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b3ad2
      to: 'on'
    condition:
      condition: time
      after: '18:00:00'
      before: '06:30:00'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.gateway_light_7811dcb38555
          brightness: 200
          color_name: deepskyblue

  - alias: Desliga Luz do Gateway
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b3ad2
      to: 'off'
      for:
        minutes: 2
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.gateway_light_7811dcb38555
          
#automação luz rua

  - alias: Liga Luz do Exterior
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b3ad2
      to: 'on'
    condition:
      condition: time
      after: '18:15:00'
      before: '06:30:00'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.yeelight_rgb_7811dce12676
          brightness: 255
          kelvin: 5000

  - alias: Desliga Luz do Exterior
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022b3ad2
      to: 'off'
      for:
        minutes: 5
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.yeelight_rgb_7811dce12676

###############################################################################
#                                                                             #
#                           l U Z E S                                         #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################      

group:

  Hall Entrada:
    control: hidden
    entities:
      - light.gateway_light_7811dcb38555
      - light.yeelight_rgb_7811dce12676
      
  Hall Sensor:
    control: hidden
    entities:
      - binary_sensor.door_window_sensor_158d00022b3ad2
 
  hall:
    view: yes
    name: Hall
    entities:
      - group.hall_entrada
      - group.hall_sensor