homeassistant:

###############################################################################
#                                                                             #
#                         B I N A R Y  S E N S O R S                          #
#                                                                             #
###############################################################################
binary_sensor:

  - platform: workday
    country: PT
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays: 
      - '2019-06-17'
      - '2019-06-18'
      - '2019-06-19'
      - '2019-06-21'
      - '2019-06-24'
      - '2019-08-01'
      - '2019-08-02'
      - '2019-08-05'
      - '2019-08-06'
      - '2019-08-07'
      - '2019-08-08'
      - '2019-08-09'
      - '2019-08-12'
      - '2019-08-13'
      - '2019-08-14'
      - '2019-08-16'
      - '2019-08-19'
      - '2019-08-20'
      - '2019-08-21'
      - '2019-08-22'
      - '2019-08-23'
      - '2019-08-26'
      - '2019-08-27'
      - '2019-08-28'
      - '2019-08-29'
      - '2019-08-30'
      - '2019-09-09'
      - '2019-09-10'
      - '2019-11-04'
      - '2019-11-05'
      - '2019-11-06'
      - '2019-11-07'
      - '2019-11-08'
      - '2019-11-11'
      - '2019-12-24'
      - '2019-12-31'