homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    binary_sensor.door_window_sensor_158d0002e7f816:
      friendly_name: Portão do Jardim
      icon: mdi:gate
    light.iluminacao_do_jardim:
      icon: mdi:lightbulb-on
    light.iluminacao_lateral:
      icon: mdi:lightbulb-on
    light.iluminacao_coberto:
      icon: mdi:lightbulb-on
###############################################################################
#                                                                             #
#                         S W I T C H                                         #
#                                                                             #
############################################################################### 
light:
  - platform: mqtt
    name: "Iluminação do Jardim"
    state_topic: "stat/jardim_iluminacao/POWER1"
    command_topic: "cmnd/jardim_iluminacao/power1"
    availability_topic: "tele/jardim_iluminacao/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Iluminação Lateral"
    state_topic: "stat/jardim_iluminacao/POWER2"
    command_topic: "cmnd/jardim_iluminacao/power2"
    availability_topic: "tele/jardim_iluminacao/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false

  - platform: mqtt
    name: "Iluminação Coberto"
    state_topic: "stat/iluminacao_coberto/POWER"
    command_topic: "cmnd/iluminacao_coberto/power"
    availability_topic: "tele/iluminacao_coberto/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
###############################################################################
#                                                                             #
#                         S E N S O R   P O R T Ã O                           #
#                                                                             #
###############################################################################      
sensor:
  - platform: template
    sensors:
      portao_jardim:
        friendly_name: "Estado Portão do Jardim"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002e7f816', 'on') %}       
            Portão Aberto
          {% else %}
            Portão Fechado
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002e7f816', 'on') %}      
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

  - alias: Ligar Iluminação do Jardim
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002e7f816
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:10:00"
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        entity_id:
          - light.iluminacao_lateral
          - light.iluminacao_do_jardim
          - light.iluminacao_coberto

  - alias: Desligar Iluminação do Jardim
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002e7f816
      to: 'off'
      for:
        minutes: 2
    action:
      - service: light.turn_off
        data_template:
          entity_id:
            - light.iluminacao_do_jardim
            - light.iluminacao_lateral
            - light.iluminacao_coberto

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             
###############################################################################      

group:

  Estado do portão do Jardim:
    control: hidden
    entities:
      - binary_sensor.door_window_sensor_158d0002e7f816

  Interruptores do Jardim:
    control: hidden
    entities:
      - light.iluminacao_do_jardim
      - light.iluminacao_lateral

  Automações do Jardim:
    control: hidden
    entities:
      - automation.ligar_iluminacao_do_jardim
      - automation.desligar_iluminacao_do_jardim

  iluminacao jardins:
    view: yes
    name: Iluminação do Jardim
    entities:
      - group.estado_do_portao_do_jardim
      - group.interruptores_do_jardim
      - group.automacoes_do_jardim