homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   


###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             #
###############################################################################      

group:

  Lâmpadas da Sala:
    control: hidden
    entities:
      - light.yeelight_rgb_7811dc6b98cb
      - light.yeelight_rgb_7811dc6b9b10
    
  Lâmpada Quarto da Mafalda:
    control: hidden
    entities:
      - light.yeelight_rgb_7811dce0fe41
      
  Lâmpada da Despensa:
    control: hidden
    entities:
      - light.yeelight_rgb_7811dc6b09nm
      
  Lâmpada Exterior da Porta:
    control: hidden
    entities:
      - light.yeelight_rgb_7811dce12676

  Led do Gateway:
    control: hidden
    entities:
      - light.gateway_light_7811dcb38555
      
  Downlights da Cozinha:
    control: hidden
    entities:
      - light.xiaomi_philips_zhirui
      - light.xiaomi_philips_zhirui_2
      
  lampadas:
    view: yes
    name: Lâmpadas
    entities:
      - group.lampadas_da_sala
      - group.lampada_quarto_da_mafalda
      - group.lampada_da_despensa
      - group.lampada_exterior_da_porta
      - group.led_do_gateway
      - group.downlights_da_cozinha