homeassistant:

###############################################################################

#                                                                             #

#                           C U S T O M I Z E                                 #

#                                                                             #

###############################################################################   

        

#  customize:




###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  

#lights:



###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             
###############################################################################      

group:

  portao:
    view: yes
    name: Portão
    entities:
      - group.portaogrupo

      

  portaogrupo:
    control: hidden
    name: Portão
    entities: