homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
  customize:
    switch.abrir_portao_pequeno:
      friendly_name: Abrir Portão Pequeno
      icon: mdi:garage
    switch.abrir_portao_grande:
      friendly_name: Abrir Portão Grande
      icon: mdi:garage
    switch.fechar_portao:
      friendly_name: Fechar Portão
      icon: mdi:garage
    script.portao_pequeno:
      friendly_name: Portão Pequeno Automático
      icon: mdi:garage
    script.portao_grande:
      friendly_name: Portão Grande Automático
      icon: mdi:garage
    binary_sensor.door_window_sensor_158d0002729eba:
      friendly_name: Portão de Entrada
      icon: mdi:door-open
    light.iluminacao_das_garagens:
      friendly_name: Interrutor das Garagens
      icon: mdi:lightbulb-on

###############################################################################
#                                                                             #
#                               S E N S O R                                   #
#                                                                             #
############################################################################### 
sensor:
  - platform: template
    sensors:
      portao_entrada:
        friendly_name: "Portão entrada"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002729eba', 'on') %}
            Aberto
          {% else %}
            Fechado
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002729eba', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
###############################################################################
#                                                                             #
#                         S W I T C H  S O N O F F                            #
#                                                                             #
###############################################################################       
switch:
  - platform: mqtt
    name: "Abrir portão grande"
    state_topic: "stat/comandoportao/POWER1"
    command_topic: "cmnd/comandoportao/power1"
    availability_topic: "tele/comandoportao/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt
    name: "Abrir portão pequeno"
    state_topic: "stat/comandoportao/POWER2"
    command_topic: "cmnd/comandoportao/power2"
    availability_topic: "tele/comandoportao/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

###############################################################################
#                                                                             #
#                            L I G H T S                                      #
#                                                                             #
############################################################################### 
light:
  - platform: mqtt
    name: "Iluminação das Garagens"
    state_topic: "stat/iluminacao_garagem/POWER"
    command_topic: "cmnd/iluminacao_garagem/power"
    availability_topic: "tele/iluminacao_garagem/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

###############################################################################
#                                                                             #
#                         S C R I P T S                                       #
#                                                                             #
###############################################################################      
script:
  portao_grande:
    sequence:
      - service: switch.turn_on
        entity_id: switch.abrir_portao_grande
      - delay: '00:00:50'
      - service: switch.turn_on
        entity_id: switch.abrir_portao_grande

  portao_pequeno:
    sequence:
      - service: switch.turn_on
        entity_id: switch.abrir_portao_pequeno
      - delay: '00:00:50'
      - service: switch.turn_on
        entity_id: switch.abrir_portao_pequeno

  portao_30:
    sequence:
      - service: switch.turn_on
        entity_id: switch.abrir_portao_pequeno
      - delay: '00:00:06'
      - service: switch.turn_on
        entity_id: switch.abrir_portao_pequeno
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#automation zigbee switch

  - alias: Interruptor para abrir portao pequeno single
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d00015aa37d
          click_type: single
    action:
      - service: switch.toggle
        data:
          entity_id: switch.abrir_portao_pequeno


  - alias: Interruptor para abrir portao grande double
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d00015aa37d
          click_type: double
    action:
      - service: switch.toggle
        data:
          entity_id: switch.abrir_portao_grande

  - alias: Interruptor para abrir portão sair a pé
    initial_state: true
    trigger:
      - platform: event
        event_type: xiaomi_aqara.click
        event_data:
          entity_id: binary_sensor.switch_158d00015aa37d
          click_type: long_click_press
    action:
      - service: script.turn_on
        data:
          entity_id: script.portao_30
#botao zigbee para iluminacao do patio

  - alias: Ligar iluminacao patio 2 lampadas
    initial_state: true
    trigger: 
      platform: state
      entity_id: sensor.0x00158d000359e754_click
      to: 'single'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.duas_lampadas_do_patio', 'off') %}
       light.turn_on  
       {%- elif is_state('group.duas_lampadas_do_patio', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.duas_lampadas_do_patio

  - alias: Ligar iluminacao patio
    initial_state: true
    trigger: 
      platform: state
      entity_id: sensor.0x00158d000359e754_click
      to: 'double'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
    action:
      service_template: >
       {% if is_state('group.lampadas_do_patio', 'off') %}
       light.turn_on  
       {%- elif is_state('group.lampadas_do_patio', 'on') -%}
       light.turn_off
       {% endif %}
      entity_id: group.lampadas_do_patio

#automation ilumination garage

  - alias: Ligar Iluminação da garagem
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      from: 'off'
      to: 'on'
    condition:
      condition: or
      conditions:
      - condition: sun
        after: sunset
        after_offset: "+00:15:00"
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        entity_id: light.iluminacao_das_garagens

  - alias: Desligar Iluminação da garagem
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'off'
      for:
        minutes: 2
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.iluminacao_das_garagens

#portao esquecido aberto semana

  - alias: Fechar portão esquecido aberto de manha
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '6'
    condition:
      - condition: time
        after: '06:00:00'
        before: '07:40:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

  - alias: Fechar portão esquecido aberto noite
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '6'
    condition:
      - condition: time
        after: '21:00:00'
        before: '00:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

#portao esquecido aberto fim semana

  - alias: Fechar portão esquecido aberto de manha fim semana
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '6'
    condition:
      - condition: time
        after: '06:00:00'
        before: '11:40:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

  - alias: Fechar portão esquecido aberto noite fim semana
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '6'
    condition:
      - condition: time
        after: '21:00:00'
        before: '00:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

#fechar portao aberto mais 15 mim semana

  - alias: Fechar portão esquecido aberto dia
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '15'
    condition:
      - condition: time
        after: '07:40:00'
        before: '21:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

  - alias: Fechar portão esquecido aberto noite
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '15'
    condition:
      - condition: time
        after: '00:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

#fechar portao aberto mais 15 mim fim semana

  - alias: Fechar portão esquecido aberto dia fim semana
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '15'
    condition:
      - condition: time
        after: '11:40:00'
        before: '21:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

  - alias: Fechar portão esquecido aberto noite fim semana
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      to: 'on'
      for:
        minutes: '15'
    condition:
      - condition: time
        after: '00:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.abrir_portao_pequeno

#notificações

  - alias: Abertura do portão pequeno
    initial_state: false
    trigger:
      platform: state
      entity_id: script.portao_pequeno
      from: 'off'
      to: 'on'
    action:
      service: notify.telegram
      data:
        message: 'Portão pequeno foi aberto'

  - alias: Abertura do portão grande
    initial_state: false
    trigger:
      platform: state
      entity_id: script.portao_grande
      from: 'off'
      to: 'on'
    action:
      service: notify.telegram
      data:
        message: 'Portão grande foi aberto'

  - alias: Portão Aberto
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      from: 'off'
      to: 'on'
    action:
      service: notify.telegram
      data:
        message: 'Portão Está Aberto'

  - alias: Portão Fechado
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002729eba
      from: 'on'
      to: 'off'
    action:
      service: notify.telegram
      data:
        message: 'Portão Está Fechado'

#desligar notificações

  - alias: Desligar Notificações portão quando em casa
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.bruno_melo
        from: 'not_home'
        to: 'home'
    condition:
    - condition: time
      after: '06:50:00'
      before: '07:59:00'
    action:
      - service: automation.turn_off
        entity_id: 
          - automation.portao_aberto
          - automation.portao_fechado

  - alias: Ligar Notificações portão quando fora casa
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.bruno_melo
        from: 'home'
        to: 'not_home'
    condition:
    - condition: time
      after: '08:00:00'
    action:
      - service: automation.turn_on
        entity_id: 
          - automation.portao_aberto
          - automation.portao_fechado


#consultar telegram

  - alias: callback Portão
    hide_entity: true
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/portao'
    action:
      - service: notify.telegram
        data:
          title: "Portão automático"
          message: "O portão está {{ states('sensor.portao_entrada') }}. Queres abrir ou fechar?"
          data:
            inline_keyboard:
              - "Abrir portão grande:/portaogrande"
              - "Abrir portão pequeno:/portaopequeno"
              - "Sair a pé:/portaoape"
              - "Fechar portao:/fecharportao"

#resposta as automacoes de cima
  - alias: 'Abrir portão a pe telegram' 
    initial_state: true
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/portaoape'            
    action:
      - service: script.turn_on
        data:
          entity_id: script.portao_30

  - alias: 'Abrir portão grande telegram' 
    initial_state: true
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/portaogrande'            
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.abrir_portao_grande

  - alias: 'Abrir portão pequeno telegram' 
    initial_state: true
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/portaopequeno'            
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.abrir_portao_pequeno

  - alias: 'Fechar portão telegram' 
    initial_state: true
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        data: '/fecharportao'            
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.abrir_portao_pequeno
###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             
###############################################################################      
group:

  Abrir e Fechar Manualmente:
    control: hidden
    entities:
       - switch.abrir_portao_grande
       - switch.abrir_portao_pequeno
       - switch.fechar_portao

  Abrir e Fechar Automático 40s:
    control: hidden
    entities:
       - script.portao_grande
       - script.portao_pequeno

  Interruptor Abrir Fechar Portão:
    control: hidden
    entities:
      - automation.interruptor_para_abrir_portao_pequeno_single
      - automation.interruptor_para_abrir_portao_grande_double
      - automation.interruptor_para_abrir_portao_sair_a_pe

  Notificar Abertura Portão:
    control: hidden
    entities:
      - automation.portao_aberto
      - automation.portao_fechado
      - automation.abertura_do_portao_pequeno
      - automation.abertura_do_portao_grande
      - automation.desligar_notificacoes_portao_quando_em_casa
      - automation.ligar_notificacoes_portao_quando_fora_casa

  Automação Portão:
    control: hidden
    entities:      
      - automation.fechar_portao_esquecido_aberto_de_manha
      - automation.fechar_portao_esquecido_aberto_noite
      - automation.ligar_iluminacao_da_garagem
      - automation.desligar_iluminacao_da_garagem

  Interruptor do Portão:
    control: hidden
    entities:
      - binary_sensor.switch_158d00015aa37d

  Interruptor das Garagens:
    control: hidden
    entities:
      - switch.iluminacao_das_garagens

  Estado do Portão Entrada:
    control: hidden
    entities:      
      - binary_sensor.door_window_sensor_158d0002729eba

  portao:
    view: yes
    icon: mdi:gate
    name: Portão
    entities:
      - group.estado_do_portao_entrada
      - group.abrir_e_fechar_manualmente
      - group.abrir_e_fechar_automatico_40s
      - group.interruptor_das_garagens
      - group.interruptor_abrir_fechar_portao
      - group.notificar_abertura_portao
      - group.interruptor_do_portao
      - group.automacao_portao