homeassistant:

###############################################################################

#                                                                             #

#                           C U S T O M I Z E                                 #

#                                                                             #

###############################################################################   

        

#  customize:




###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#automação mudar fraldas quarto

  - alias: Mudar fraldas quarto ON
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '22:30:00'
      before: '06:50:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dce0fe41
        data:
          brightness: 70
          color_name: orangered
      - service: light.turn_on
        data:
          entity_id: binary_sensor.motion_sensor_158d0001f9d417

  - alias: Mudar fraldas quarto OFF
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 4
    condition:
    - condition: time
      after: '22:30:00'
      before: '06:50:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dce0fe41
      - service: light.turn_off
        data:
          entity_id: binary_sensor.motion_sensor_158d0001f9d417

###############################################################################
#                                                                             #
#                           S W I T C H E S                                   #
#                                                                             #
###############################################################################  

#lights:

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             
###############################################################################      

group:

  quartomafalda:
    view: yes
    name: quarto mafalda
    entities:
      - group.quartomafaldagrupo

      

  quartomafaldagrupo:
    control: hidden
    name: Quarto Mafalda
    entities:
      - light.yeelight_rgb_7811dce0fe41
      - automation.mudar_fraldas_quarto_on
      - automation.mudar_fraldas_quarto_off