script:

  radio_comercial:
   alias: Radio Comercial
   sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.sala
        volume_level: '0.30'
    -  service: media_player.play_media
       data_template:
        entity_id: media_player.sala
        media_content_id: http://mcrscast1.mcr.iol.pt/comercial.mp3
        media_content_type: 'audio/mp4'

  rfm:
   alias: RFM
   sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.sala
        volume_level: '0.30'
    -  service: media_player.play_media
       data_template:
        entity_id: media_player.sala
        media_content_id: http://19553.live.streamtheworld.com:3690/RFM_SC
        media_content_type: 'audio/mp4'

  m80:
   alias: M80
   sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.sala
        volume_level: '0.30'
    -  service: media_player.play_media
       data_template:
        entity_id: media_player.sala
        media_content_id: http://mcrscast.mcr.iol.pt/m80
        media_content_type: 'audio/mp4'

  vodafone:
   alias: Vodafone
   sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.sala
        volume_level: '0.30'
    -  service: media_player.play_media
       data_template:
        entity_id: media_player.sala
        media_content_id: http://195.23.102.207/vodafone
        media_content_type: 'audio/mp4'

  radio_stop:
    alias: Parar rádio
    sequence:
      - service: media_player.media_stop
        data:
          entity_id: media_player.sala

automation:

  - alias: Ligar radio de manha
    initial_state: true
    trigger:
      - platform: time
        at: "07:15:00"
    condition:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.sala
          volume_level: '0.30'
      -  service: media_player.play_media
         data_template:
          entity_id: media_player.sala
          media_content_id: http://mcrscast1.mcr.iol.pt/comercial.mp3
          media_content_type: 'audio/mp4'