homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   

###############################################################################
#                                                                             #
#                         INPUT   BOOLEAN                                     #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

#Automaçóes cubo


  - alias: Cubo 90 graus
    initial_state: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00027984b3
        action_type: flip90
    action:
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_17h00_19h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_00h00_06h50
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_17h_19h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_00h00_06h50
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 255
          kelvin: 6500
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 255
          kelvin: 6500

          
  - alias: Cubo 180 graus
    initial_state: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00027984b3
        action_type: flip180
    action:
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_17h00_19h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_00h00_06h50
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_17h_19h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_00h00_06h50
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 150
          kelvin: 3000
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 150
          kelvin: 3000

  - alias: Cubo All OFF
    initial_state: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00027984b3
        action_type: shake_air
    action:
      - service: automation.turn_on
        entity_id: automation.ligar_candeeiros_sala_17h00_19h30
      - service: automation.turn_on
        entity_id: automation.ligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_on
        entity_id: automation.ligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_on
        entity_id: automation.ligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_on
        entity_id: automation.ligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_on
        entity_id: automation.ligar_candeeiros_sala_00h00_06h50
      - service: automation.turn_on
        entity_id: automation.desligar_candeeiros_sala_17h_19h30
      - service: automation.turn_on
        entity_id: automation.desligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_on
        entity_id: automation.desligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_on
        entity_id: automation.desligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_on
        entity_id: automation.desligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_on
        entity_id: automation.desligar_candeeiros_sala_00h00_06h50
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb


  - alias: Cubo Empurrar
    initial_state: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00027984b3
        action_type: move
    action:
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_17h00_19h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_00h00_06h50
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_17h_19h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_00h00_06h50
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 150
          color_name: orangered
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 150
          color_name: orangered


  - alias: Cubo 2 Batidas
    initial_state: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d00027984b3
        action_type: tap_twice
    action:
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_17h00_19h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.ligar_candeeiros_sala_00h00_06h50
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_17h_19h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_19h30_20h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_20h30_21h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_21h30_22h30
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_22h30_00h00
      - service: automation.turn_off
        entity_id: automation.desligar_candeeiros_sala_00h00_06h50
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 100
          color_name: cornflowerblue
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 100
          color_name: cornflowerblue

#automaçóes Sala
 
  - alias: Ligar Candeeiros Sala 17h00 19h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '17:00:00'
      before: '19:30:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 255
          kelvin: 6500
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 255
          kelvin: 6500


  - alias: Desligar Candeeiros Sala 17h 19h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      after: '17:00:00'
      before: '19:30:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb

        
  - alias: Ligar Candeeiros Sala 19h30 20h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '19:30:00'
      before: '20:30:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 200
          kelvin: 4300
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 200
          kelvin: 4300


  - alias: Desligar Candeeiros Sala 19h30 20h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      after: '19:30:00'
      before: '20:30:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb


  - alias: Ligar Candeeiros Sala 20h30 21h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '20:30:00'
      before: '21:30:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 100
          kelvin: 3400
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 100
          kelvin: 3400


  - alias: Desligar Candeeiros Sala 20h30 21h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      after: '20:30:00'
      before: '21:30:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb

          
  - alias: Ligar Candeeiros Sala 21h30 22h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '21:30:00'
      before: '22:30:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 76
          color_name: aqua
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 76
          color_name: aqua


  - alias: Desligar Candeeiros Sala 21h30 22h30
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 10
    condition:
    - condition: time
      after: '21:30:00'
      before: '22:30:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb


  - alias: Ligar Candeeiros Sala 22h30 00h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '22:30:00'
      before: '00:00:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 85
          color_name: blue
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 85
          color_name: blue

 
  - alias: Desligar Candeeiros Sala 22h30 00h00
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    condition:
    - condition: time
      after: '22:30:00'
      before: '00:00:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10

          
  - alias: Ligar Candeeiros Sala 00h00 06h50
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'off'
      to: 'on'
    condition:
    - condition: time
      after: '00:00:00'
      before: '06:50:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      below: 10
    action:
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b98cb
        data:
          brightness: 50
          color_name: green
      - service: light.turn_on
        entity_id: light.yeelight_rgb_7811dc6b9b10
        data:
          brightness: 50
          color_name: green

 
  - alias: Desligar Candeeiros Sala 00h00 06h50
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      from: 'on'
      to: 'off'
      for:
        minutes: 3
    condition:
    - condition: time
      after: '00:00:00'
      before: '06:50:00'
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10

         
  - alias: Desligar Candeeiros a Cima dos 20 lx
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f9d417
      to: 'off'
      for: 
        seconds: 15
    condition:
    - condition: time
      after: '17:00:00'
      before: '06:50:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d0001f9d417
      above: 30
    action:
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b98cb
      - service: light.turn_off
        entity_id: light.yeelight_rgb_7811dc6b9b10
          

###############################################################################
#                                                                             #
#                           L U Z E S                                         #
#                                                                             #
###############################################################################  

###############################################################################
#                                                                             #
#                         G R O U P S                                         #
#                                                                             
###############################################################################      

group:

  Lâmpadas da Sala:
    control: hidden
    entities:
      - light.yeelight_rgb_7811dc6b9b10
      - light.yeelight_rgb_7811dc6b98cb
      
  Sensor de Movimento:
    control: hidden
    entities:
      - binary_sensor.motion_sensor_158d0001f9d417
      - sensor.illumination_158d0001f9d417
      - sensor.illumination_7811dcb38555
      
  Sensor de Temperatura:
    control: hidden
    entities:
      - sensor.temperature_158d00023203e4
      - sensor.humidity_158d00023203e4

      
  Cubo Mágico:
    control: hidden
    entities:
      - binary_sensor.cube_158d00027984b3

  sala:
    view: yes
    name: sala
    entities:
      - group.lampadas_da_sala
      - group.sensor_de_movimento
      - group.sensor_de_temperatura
      - group.cubo_magico