homeassistant:

camera:
  - platform: generic
    name: spotify_album_cover
    still_image_url: https://192.168.1.133:8123{{ states.media_player.spotify.attributes.entity_picture }}
#   _____                                    
#  / ____|                                   
# | (___   ___ _ __  ___  ___  _ __ ___  ___ 
#  \___ \ / _ \ '_ \/ __|/ _ \| '__/ _ \/ __|
#  ____) |  __/ | | \__ \ (_) | | |  __/\__ \
# |_____/ \___|_| |_|___/\___/|_|  \___||___/
