homeassistant:

zone:

  - name: home
    latitude: !secret latitude_casa
    longitude: !secret longitude_casa
    radius: 70
    icon: mdi:home

  - name: notrabalhobruno
    latitude: !secret latitude_trabalho_bruno
    longitude: !secret longitude_trabalho_bruno
    radius: 100
    icon: mdi:seat-recline-normal
    
  - name: noginasiobruno
    latitude: !secret latitude_ginasio_bruno
    longitude: !secret longitude_ginasio_bruno
    radius: 30
    icon: mdi:google-fit

  - name: notrabalhoarmanda
    latitude: !secret latitude_trabalho_armanda
    longitude: !secret longitude_trabalho_armanda
    radius: 70
    icon: mdi:doctor

device_tracker:
  
  - platform: mqtt_json
    devices:
     bruno: zanzito/bruno/location
    track_new_devices: True
    interval_seconds: 10
    consider_home: 20

sensor:
  
  - platform: mqtt
    state_topic: "zanzito/bruno/battery_level"
    name: "Bateria tlm Bruno"
    unit_of_measurement: '%'
    retain: true
       
  - platform: template
    sensors:       
      bruno:
        friendly_name: 'Localização Bruno'
        value_template: > 
          {%- if is_state('device_tracker.bruno', 'not_home') -%}
             Ausente
          {%- endif -%}
          {%- if is_state('device_tracker.bruno', 'home') -%}
             Em Casa
          {%- endif -%}      
          {%- if is_state('device_tracker.bruno', 'notrabalhobruno') -%} 
             No Trabalho
          {%- endif -%}
          {%- if is_state('device_tracker.bruno', 'noginasiobruno') -%} 
             No Ginásio
          {%- endif -%}

camera:
  
  - name: bruno_cam
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.bruno.attributes.latitude }},{{ states.device_tracker.bruno.attributes.longitude }}&zoom=16&size=500x500&maptype=satellite&markers=color:green%7Clabel:JA%7C{{ states.device_tracker.bruno.attributes.latitude }},{{ states.device_tracker.bruno.attributes.longitude }}&key=!secret geocode_api_key
    limit_refetch_to_url_change: true 

group:

  zanzito:
    name: Localização
    entities:
      - sensor.bruno
      - sensor.bateria_tlm_bruno
      - camera.bruno_cam
      - sensor.bruno_melo