 
# comunicaçao do payloa do sensor de movimento
# podes retirar informaçao dos payload existentes em payload {"illuminance":36,"linkquality":168,"occupancy":true}


 # zigbee2mqtt:info 6/23/2019, 4:24:34 PM MQTT publish: topic 'zigbee2mqtt/sensor_movimento_sala', payload #'{"illuminance":36,"linkquality":168,"occupancy":true}' 


#sensor movimento xiaomi
binary_sensor:

  - platform: mqtt
    name: movimento sala
    state_topic: "zigbee2mqtt/movimento_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: motion
    qos: 1

#sensor janela quarto mafalda
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/janela_mafalda"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "window"

#sensor janela sala
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/janela_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "window"

#sensor movimento sala xiaomi
sensor:
  - platform: mqtt
    name: "lx sala"
    state_topic: "zigbee2mqtt/movimento_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "lux"
    icon: mdi:speedometer
    value_template: "{{ value_json.illuminance }}"

  - platform: mqtt
    name: "sinal DB"
    state_topic: "zigbee2mqtt/movimento_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "db"
    icon: mdi:speedometer
    value_template: "{{ value_json.linkquality }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/movimento_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

#tomada ikea corredor
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/tomada_hall"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "db"
    value_template: "{{ value_json.linkquality }}"

#tomada ikea sala
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/tomada_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

#botao ikea
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/botao_leds"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/botao_leds"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/botao_leds"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

#botao iluminacao exterior xiaomi
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/botao_ilu_exterior"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/botao_ilu_exterior"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/botao_ilu_exterior"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

#sensor janela quarto mafalda
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/janela_mafalda"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/janela_mafalda"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

#sensor janela da sala
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/janela_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"

  - platform: "mqtt"
    state_topic: "zigbee2mqtt/janela_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

#tomada ikea corredor
switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/tomada_hall"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tomada_hall/set"

#tomada ikea sala
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/tomada_sala"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/tomada_sala/set"