homeassistant:

#  ______                     
# |___  /                     
#    / / ___  _ __   __ _ ___ 
#   / / / _ \| '_ \ / _` / __|
#  / /_| (_) | | | | (_| \__ \
# /_____\___/|_| |_|\__,_|___/

zone:

  - name: home
    latitude: !secret latitude_casa
    longitude: !secret longitude_casa
    radius: 50
    icon: mdi:home

  - name: notrabalhobruno
    latitude: !secret latitude_trabalho_bruno
    longitude: !secret longitude_trabalho_bruno
    radius: 60
    icon: mdi:seat-recline-normal
    
  - name: noginasiobruno
    latitude: !secret latitude_ginasio_bruno
    longitude: !secret longitude_ginasio_bruno
    radius: 30
    icon: mdi:google-fit

  - name: notrabalhoarmanda
    latitude: !secret latitude_trabalho_armanda
    longitude: !secret longitude_trabalho_armanda
    radius: 70
    icon: mdi:doctor

  - name: lidl
    latitude: !secret latitude_lidl
    longitude: !secret longitude_lidl
    radius: 70
    icon: mdi:cart

  - name: continente
    latitude: !secret latitude_continente
    longitude: !secret longitude_continente
    radius: 70
    icon: mdi:cart

#   _____                                    
#  / ____|                                   
# | (___   ___ _ __  ___  ___  _ __ ___  ___ 
#  \___ \ / _ \ '_ \/ __|/ _ \| '__/ _ \/ __|
#  ____) |  __/ | | \__ \ (_) | | |  __/\__ \
# |_____/ \___|_| |_|___/\___/|_|  \___||___/

sensor:
       
  - platform: template
    sensors:       
      bruno:
        friendly_name: 'Localização Bruno'
        value_template: >
          {%- if is_state('device_tracker.mi_a1', 'not_home') -%}
             Ausente
          {%- endif -%}
          {%- if is_state('device_tracker.mi_a1', 'home') -%}
             Em Casa
          {%- endif -%}      
          {%- if is_state('device_tracker.mi_a1', 'notrabalhobruno') -%} 
             No trabalho
          {%- endif -%}
          {%- if is_state('device_tracker.mi_a1', 'noginasiobruno') -%} 
             No Ginásio
          {%- endif -%}
          {%- if is_state('device_tracker.mi_a1', 'lidl') -%} 
             No Lidl
          {%- endif -%}
          {%- if is_state('device_tracker.mi_a1', 'continente') -%} 
             No Continente
          {%- endif -%}

  - platform: template
    sensors:       
      armanda:
        friendly_name: 'Localização Armanda'
        value_template: >
          {%- if is_state('device_tracker.armanda_rodrigues', 'not_home') -%}
             Ausente
          {%- endif -%}
          {%- if is_state('device_tracker.armanda_rodrigues', 'home') -%}
             Em Casa
          {%- endif -%}      
          {%- if is_state('device_tracker.armanda_rodrigues', 'notrabalhoarmanda') -%} 
             No trabalho
          {%- endif -%}
          {%- if is_state('device_tracker.armanda_rodrigues', 'lidl') -%} 
             No Lidl
          {%- endif -%}
          {%- if is_state('device_tracker.armanda_rodrigues', 'continente') -%} 
             No Continente
          {%- endif -%}